{"uuid": "97ffe52c-3d8f-4c43-8f94-36e201ff3788", "children": ["122bad6c-46b5-41b4-82ca-e5e91081c93c"], "befores": [{"name": "http", "status": "skipped", "statusDetails": {"message": "Skipped: API not reachable at http://127.0.0.1:8000. Start it with: uvicorn server.main:app --port 8000\n", "trace": "  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"c:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\tests\\conftest.py\", line 59, in http\n    pytest.skip(f\"API not reachable at {BASE_URL}. \"\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                f\"Start it with: uvicorn server.main:app --port {API_PORT}\")\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asusv\\OneDrive\\Desktop\\ai-agent-test-framework\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 159, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n"}, "start": 1755095192811, "stop": 1755095193316}], "start": 1755095192811, "stop": 1755095193335}